(1-2)初級 入力値エラー処理
Mmy26/ex-vue-emp-manage-bugfix pull request #3
Opened 2022-02-21 05:25 UTC by Mmy26

入力値エラー処理(未入力値チェック)の実装の修正を行いましたので、レビューをお願いします。

問題があれば、コメントをいただければと思います。
特に問題がなければマージをお願いします。

2022-02-21 06:53 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 06:53 UTC, igamasayuki commented on src/views/RegisterAdmin.vue
> +      this.lastName != "" ||
こちらですが、１つ１つの入力項目をチェックしていただき、それぞれの入力欄上に「○○が入力されていません」という赤いエラーメッセージを出すようにしてください。

2022-02-21 08:21 UTC, Mmy26 commented on src/views/RegisterAdmin.vue
> +      this.lastName != "" ||
エラーメッセージの修正を行いましたのでレビューをお願いします。
問題があれば、コメントをいただければと思います。
特に問題がなければマージをお願いします。

2022-02-22 00:10 UTC, igamasayuki approved these changes
気になる点をコメントしました。
承認しますが、必要であれば後ほど修正をしておきましょう。

2022-02-22 00:10 UTC, igamasayuki commented on src/views/RegisterAdmin.vue
> +  private formChecker = true;
formCheckerよりもhasErrorsという変数名の方が後から見てわかりやすいです。

2022-02-22 00:10 UTC, merged