(1-4)中級 確認用パスワード
Mmy26/ex-vue-emp-manage-bugfix pull request #4
Opened 2022-02-21 06:26 UTC by Mmy26

確認用パスワードの実装を行いましたのでレビューをお願いします。

問題があればコメントをいただければと思います。
特に問題がなければマージをお願いします。

2022-02-21 06:55 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 06:55 UTC, igamasayuki commented on src/views/RegisterAdmin.vue
> +    if (this.password === this.passwordConfirm) {
if文が入れ子になってとても読みづらくなっています。

if(もしパスワードが一致していなかったら){
　エラーメッセージを出す
 　return;
}

今までの処理


という流れに修正をお願いします。

2022-02-21 08:27 UTC, Mmy26 commented on src/views/RegisterAdmin.vue
> +    if (this.password === this.passwordConfirm) {
条件分岐の入れ子を修正しましたのでレビューをお願いします。
問題があればコメントをいただければと思います。
特に問題がなければマージをお願いします。

2022-02-22 00:11 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-02-22 00:14 UTC, merged